### ISSUE TITLE
The plugin passes even when ChartMuseum returns 404

### ISSUE THREAD

**Issue by regner** [honestbee/drone-chartmuseum#5]
I am still working on figuring out why ChartMuseum is returning a 404 but it is. I can see in the logs of ChartMuseum the 404:

```json
{"L":"WARN","T":"2018-12-06T08:45:50.759Z","M":"[5662] Request served","path":"/api/charts","comment":"","latency":"60.309µs","clientIP":"1.2.3.4","method":"POST","statusCode":404,"reqID":"2fdc5bfb-0b44-4b93-b66c-d2ac44897a7a"}
```

With the 404 occuring the plugin passes. Here is my .drone.yml

```yaml
pipeline:
  chartmuseum-all:
    image: quay.io/honestbee/drone-chartmuseum
    repo_url: http://chartmuseum-chartmuseum:8080
    when:
      branch:
      - master
```
